/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2024-12-30 08:15:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/footer.jsp", Long.valueOf(1735546139216L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1731463723702L));
    _jspx_dependants.put("jar:file:/D:/cloud/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Solocare/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/navbar.jsp", Long.valueOf(1735546355478L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>SoloCare</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("    <link href=\"//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSansNeo.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://unpkg.com/aos@2.3.1/dist/aos.css\" />\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        body {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            font-family: 'Spoqa Han Sans Neo', sans-serif;\r\n");
      out.write("            background-color: #fefefe;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            scroll-behavior: smooth;\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .menu-logo {\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            letter-spacing: -0.5px;\r\n");
      out.write("        }\r\n");
      out.write("        .menu-links a {\r\n");
      out.write("            color: #333;\r\n");
      out.write("            margin-left: 20px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 0.95rem;\r\n");
      out.write("            transition: color 0.2s;\r\n");
      out.write("        }\r\n");
      out.write("        .menu-links a:hover {\r\n");
      out.write("            color: #000;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("        #heroSection {\r\n");
      out.write("            height: 80vh; \r\n");
      out.write("            position: relative; \r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            overflow: hidden; \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #heroSection::before {\r\n");
      out.write("            content: \"\";\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background-image: url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/shop.jpg');\r\n");
      out.write("            background-size: cover; \r\n");
      out.write("            background-position: center; \r\n");
      out.write("            opacity: 0.5;\r\n");
      out.write("            z-index: -1; \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hero-content {\r\n");
      out.write("            max-width: 600px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            position: relative; \r\n");
      out.write("            z-index: 1; \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hero-content h1 {\r\n");
      out.write("            font-size: 3rem;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("            color: #2c3e50; \r\n");
      out.write("            animation: fadeInDown 1s ease-out;\r\n");
      out.write("        }\r\n");
      out.write("        .hero-content p {\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("            margin-bottom: 2rem;\r\n");
      out.write("            color: #34495e; \r\n");
      out.write("            animation: fadeInUp 1s ease-out;\r\n");
      out.write("        }\r\n");
      out.write("		.btn-hero,\r\n");
      out.write("		.btn-hero:focus,\r\n");
      out.write("		.btn-hero:active,\r\n");
      out.write("		.btn-hero:hover,\r\n");
      out.write("		.btn-hero:visited {\r\n");
      out.write("		    display: inline-block;\r\n");
      out.write("		    padding: 12px 24px;\r\n");
      out.write("		    background: #D3D3D3;\r\n");
      out.write("		    color: #000000; \r\n");
      out.write("		    text-decoration: none;\r\n");
      out.write("		    border-radius: 6px;\r\n");
      out.write("		    font-size: 1rem;\r\n");
      out.write("		    transition: background 0.3s, transform 0.3s, box-shadow 0.3s, color 0.3s;\r\n");
      out.write("		    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.btn-hero:hover {\r\n");
      out.write("		    background: #E0E0E0; \r\n");
      out.write("		    color: #000000; /\r\n");
      out.write("		    transform: translateY(-2px);\r\n");
      out.write("		    box-shadow: 0 6px 12px rgba(0, 0, 0, 0.2);\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("        @keyframes fadeInDown {\r\n");
      out.write("            from {\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("                transform: translateY(-20px);\r\n");
      out.write("            }\r\n");
      out.write("            to {\r\n");
      out.write("                opacity: 1;\r\n");
      out.write("                transform: translateY(0);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes fadeInUp {\r\n");
      out.write("            from {\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("                transform: translateY(20px);\r\n");
      out.write("            }\r\n");
      out.write("            to {\r\n");
      out.write("                opacity: 1;\r\n");
      out.write("                transform: translateY(0);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #bodyWrapper {\r\n");
      out.write("            padding: 20px 40px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .category-sidebar {\r\n");
      out.write("            position: -webkit-sticky;\r\n");
      out.write("            position: sticky;\r\n");
      out.write("            top: 80px;\r\n");
      out.write("            \r\n");
      out.write("            background: #fff;\r\n");
      out.write("            border: 1px solid #eee;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            box-shadow: 0 4px 12px rgba(0,0,0,0.05);\r\n");
      out.write("\r\n");
      out.write("            max-height: calc(100vh - 100px);\r\n");
      out.write("            overflow-y: auto;\r\n");
      out.write("        }\r\n");
      out.write("        .category-sidebar h4 {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("        .category-list, .category-list ul, .category-list li {\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .category-list input[type=\"radio\"] {\r\n");
      out.write("            appearance: none;\r\n");
      out.write("            width: 0; height: 0;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            outline: none;\r\n");
      out.write("        }\r\n");
      out.write("        .category-list input[type=\"radio\"]:checked + label {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #000;\r\n");
      out.write("        }\r\n");
      out.write("        .category-list label {\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            font-size: 0.95rem;\r\n");
      out.write("            line-height: 1.5;\r\n");
      out.write("            display: block;\r\n");
      out.write("            padding: 4px 0;\r\n");
      out.write("        }\r\n");
      out.write("        .subcategory {\r\n");
      out.write("            display: none;\r\n");
      out.write("            margin-left: 12px;\r\n");
      out.write("            border-left: 1px solid #eee;\r\n");
      out.write("            padding-left: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .subcategory.visible {\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-category-search,\r\n");
      out.write("        .btn-user-search {\r\n");
      out.write("            display: block;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            background: #000;\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 8px 0;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            margin-top: 12px;\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("            transition: background 0.2s;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-category-search:hover, .btn-user-search:hover {\r\n");
      out.write("            background: #333;\r\n");
      out.write("        }\r\n");
      out.write("        .user-search-form {\r\n");
      out.write("            margin-top: 24px;\r\n");
      out.write("            padding-top: 16px;\r\n");
      out.write("            border-top: 1px solid #eee;\r\n");
      out.write("        }\r\n");
      out.write("        .user-search-form .form-control {\r\n");
      out.write("            background: #fff;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            margin-bottom: 8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-grid {\r\n");
      out.write("            margin-left: 0; \r\n");
      out.write("            margin-right: 0; \r\n");
      out.write("        }\r\n");
      out.write("        .card {\r\n");
      out.write("            background: #fff;\r\n");
      out.write("            border: 1px solid #eee;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            box-shadow: 0 2px 8px rgba(0,0,0,0.04);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            transition: transform 0.2s, box-shadow 0.2s;\r\n");
      out.write("        }\r\n");
      out.write("        .card:hover {\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 6px 16px rgba(0,0,0,0.08);\r\n");
      out.write("        }\r\n");
      out.write("        .card-img-top {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 180px;\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("            background-color: #f8f8f8;\r\n");
      out.write("        }\r\n");
      out.write("        .card-body {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            padding: 16px;\r\n");
      out.write("            flex: 1;\r\n");
      out.write("        }\r\n");
      out.write("        .card-brand {\r\n");
      out.write("            font-size: 0.85rem;\r\n");
      out.write("            color: #666;\r\n");
      out.write("            margin-bottom: 4px;\r\n");
      out.write("        }\r\n");
      out.write("        .card-product-name {\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            margin-bottom: 6px;\r\n");
      out.write("            color: #000;\r\n");
      out.write("        }\r\n");
      out.write("        .card-price {\r\n");
      out.write("            font-size: 0.95rem;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            margin-bottom: 12px;\r\n");
      out.write("            color: #444;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-primary {\r\n");
      out.write("            align-self: flex-start;\r\n");
      out.write("            background: #000 !important;\r\n");
      out.write("            border: none !important;\r\n");
      out.write("            color: #fff !important;\r\n");
      out.write("            border-radius: 6px !important;\r\n");
      out.write("            padding: 6px 12px !important;\r\n");
      out.write("            font-size: 0.9rem !important;\r\n");
      out.write("            transition: background 0.2s;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-primary:hover {\r\n");
      out.write("            background: #333 !important;\r\n");
      out.write("        }\r\n");
      out.write("        .section-title {\r\n");
      out.write("            font-weight: 700; /* 폰트 두께 증가 */\r\n");
      out.write("            font-size: 1.5rem; /* 폰트 크기 증가 */\r\n");
      out.write("            margin: 24px 0 12px;\r\n");
      out.write("            letter-spacing: -0.3px;\r\n");
      out.write("            color: #2c3e50; /* 색상 변경 */\r\n");
      out.write("        }\r\n");
      out.write("        .section-subtitle {\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            font-size: 1.1rem; /* 폰트 크기 증가 */\r\n");
      out.write("            margin: 0 0 16px;\r\n");
      out.write("            color: #34495e; /* 색상 변경 */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 반응형 디자인 */\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            #menuWrapper {\r\n");
      out.write("                padding: 0 20px;\r\n");
      out.write("                height: 56px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            #heroSection {\r\n");
      out.write("                height: 60vh;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .hero-content h1 {\r\n");
      out.write("                font-size: 2.5rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .hero-content p {\r\n");
      out.write("                font-size: 1rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-hero {\r\n");
      out.write("                padding: 10px 20px;\r\n");
      out.write("                font-size: 0.9rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .category-sidebar {\r\n");
      out.write("                padding: 15px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .section-title {\r\n");
      out.write("                font-size: 1.3rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .section-subtitle {\r\n");
      out.write("                font-size: 1rem;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("  <title>솔로케어</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <link\r\n");
      out.write("    rel=\"stylesheet\"\r\n");
      out.write("    href=\"https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css\"\r\n");
      out.write("  />\r\n");
      out.write("  <link\r\n");
      out.write("    href=\"https://webfontworld.github.io/gmarket/GmarketSans.css\"\r\n");
      out.write("    rel=\"stylesheet\"\r\n");
      out.write("  />\r\n");
      out.write("\r\n");
      out.write("  <link\r\n");
      out.write("    href=\"https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap\"\r\n");
      out.write("    rel=\"stylesheet\"\r\n");
      out.write("  />\r\n");
      out.write("\r\n");
      out.write("  <style>\r\n");
      out.write("    :root {\r\n");
      out.write("      --font-pretendard: 'Pretendard', -apple-system, BlinkMacSystemFont, system-ui,\r\n");
      out.write("        Roboto, 'Helvetica Neue', 'Segoe UI', 'Apple SD Gothic Neo',\r\n");
      out.write("        'Noto Sans KR', 'Malgun Gothic', sans-serif;\r\n");
      out.write("      --font-gmarket: 'GmarketSans', sans-serif;\r\n");
      out.write("      --font-montserrat: 'Montserrat', sans-serif; \r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      font-family: var(--font-pretendard);\r\n");
      out.write("      letter-spacing: -0.01em;\r\n");
      out.write("      padding-top: 70px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .custom-nav {\r\n");
      out.write("      position: fixed;\r\n");
      out.write("      top: 0;\r\n");
      out.write("      left: 0;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      z-index: 1000;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      justify-content: space-between;\r\n");
      out.write("      background-color: rgba(255, 255, 255, 0.8);\r\n");
      out.write("      backdrop-filter: saturate(180%) blur(10px);\r\n");
      out.write("      border-bottom: none;\r\n");
      out.write("      box-shadow: none;\r\n");
      out.write("      padding: 10px 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* 로고 */\r\n");
      out.write("    .custom-nav .logo {\r\n");
      out.write("      flex: 0 0 auto; \r\n");
      out.write("    }\r\n");
      out.write("    .custom-nav .logo a {\r\n");
      out.write("      font-family: var(--font-montserrat);\r\n");
      out.write("      font-weight: 700;\r\n");
      out.write("      font-size: 32px;\r\n");
      out.write("      color: #000;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      letter-spacing: -0.02em;\r\n");
      out.write("      transition: opacity 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("    .custom-nav .logo a:hover {\r\n");
      out.write("      opacity: 0.7;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .custom-nav .menu {\r\n");
      out.write("      margin: 0 auto; \r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      gap: 60px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .custom-nav .menu a {\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      color: #333;\r\n");
      out.write("      font-size: 16px;\r\n");
      out.write("      font-weight: 500;\r\n");
      out.write("      transition: color 0.2s ease, opacity 0.2s ease;\r\n");
      out.write("      opacity: 0.9;\r\n");
      out.write("    }\r\n");
      out.write("    .custom-nav .menu a:hover {\r\n");
      out.write("      color: #000;\r\n");
      out.write("      opacity: 1;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* 드롭다운 (서브메뉴) 공통 */\r\n");
      out.write("    .custom-nav .menu-item {\r\n");
      out.write("      position: relative;\r\n");
      out.write("    }\r\n");
      out.write("    .custom-nav .menu-item .dropdown {\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: calc(100% + 10px);\r\n");
      out.write("      left: 50%;\r\n");
      out.write("      transform: translateX(-50%);\r\n");
      out.write("      min-width: 220px;\r\n");
      out.write("\r\n");
      out.write("      background-color: rgba(255, 255, 255, 0.95);\r\n");
      out.write("      box-shadow: 0 8px 20px rgba(0, 0, 0, 0.08);\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      border: 1px solid rgba(0, 0, 0, 0.05);\r\n");
      out.write("\r\n");
      out.write("      visibility: hidden;\r\n");
      out.write("      opacity: 0;\r\n");
      out.write("      transition: visibility 0s, opacity 0.4s ease, transform 0.4s ease;\r\n");
      out.write("      transform: translate(-50%, 20px);\r\n");
      out.write("\r\n");
      out.write("      display: flex;\r\n");
      out.write("      flex-direction: column;\r\n");
      out.write("      padding: 8px 0;\r\n");
      out.write("      white-space: nowrap;\r\n");
      out.write("      z-index: 9999;\r\n");
      out.write("    }\r\n");
      out.write("    .custom-nav .menu-item:hover .dropdown {\r\n");
      out.write("      visibility: visible;\r\n");
      out.write("      opacity: 1;\r\n");
      out.write("      transform: translate(-50%, 0);\r\n");
      out.write("    }\r\n");
      out.write("    .custom-nav .menu-item .dropdown a {\r\n");
      out.write("      display: block;\r\n");
      out.write("      padding: 12px 20px;\r\n");
      out.write("      font-size: 14px;\r\n");
      out.write("      color: #333;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      transition: background-color 0.2s ease;\r\n");
      out.write("      border-radius: 6px;\r\n");
      out.write("    }\r\n");
      out.write("    .custom-nav .menu-item .dropdown a:hover {\r\n");
      out.write("      background-color: rgba(0, 0, 0, 0.04);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .custom-nav .submenu {\r\n");
      out.write("      position: relative;\r\n");
      out.write("    }\r\n");
      out.write("    .custom-nav .submenu .dropdown {\r\n");
      out.write("      top: 0;\r\n");
      out.write("      left: 100%;\r\n");
      out.write("      transform: translateX(10px);\r\n");
      out.write("      min-width: 130px;\r\n");
      out.write("      margin-left: 2px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .custom-nav .user-actions {\r\n");
      out.write("      flex: 0 0 auto;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      gap: 15px;\r\n");
      out.write("    }\r\n");
      out.write("    .custom-nav .user-actions .welcome {\r\n");
      out.write("      margin-right: 10px;\r\n");
      out.write("      font-size: 15px;\r\n");
      out.write("      font-weight: 500;\r\n");
      out.write("      color: #333;\r\n");
      out.write("      opacity: 0.9;\r\n");
      out.write("    }\r\n");
      out.write("    .custom-nav .user-actions a {\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      color: #000;\r\n");
      out.write("      font-weight: 600;\r\n");
      out.write("      font-size: 14px;\r\n");
      out.write("      padding: 8px 16px;\r\n");
      out.write("      border: none;\r\n");
      out.write("      border-radius: 8px;\r\n");
      out.write("      background-color: #f1f1f1;\r\n");
      out.write("      transition: background-color 0.2s ease, color 0.2s ease;\r\n");
      out.write("    }\r\n");
      out.write("    .custom-nav .user-actions a:hover {\r\n");
      out.write("      background-color: #ddd;\r\n");
      out.write("      color: #000;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

    
    boolean isLoggedIn = request.getSession().getAttribute("mem") != null;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"custom-nav\">\r\n");
      out.write("  <!-- 로고 -->\r\n");
      out.write("  <div class=\"logo\">\r\n");
      out.write("    <a href=\"/Solocare/home\">SoloCare</a>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- 메뉴 -->\r\n");
      out.write("  <div class=\"menu\">\r\n");
      out.write("    <a href=\"/Solocare/search\">쇼핑</a>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"menu-item\">\r\n");
      out.write("      <a href=\"#\">동호회</a>\r\n");
      out.write("      <div class=\"dropdown\">\r\n");
      out.write("        <a href=\"/Solocare/club/list\">\r\n");
      out.write("          동호회 목록<br><span>다양한 동호회를 한눈에 확인</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"/Solocare/club/myclub?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mem.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("          내 동호회<br><span>내가 속한 동호회 확인</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"menu-item\">\r\n");
      out.write("      <a href=\"#\">커뮤니티</a>\r\n");
      out.write("      <div class=\"dropdown\">\r\n");
      out.write("        <a href=\"/Solocare/board?category=tip&page=1\">\r\n");
      out.write("          정보공유<br><span>생활 팁과 유용한 정보 공유</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"/Solocare/board?category=free\">\r\n");
      out.write("          자유 게시판<br><span>자유롭게 의견과 경험을 나누는 공간</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"submenu\">\r\n");
      out.write("          <a href=\"#\">\r\n");
      out.write("            중고 거래<br><span>필요 없는 물품을 거래하는 공간</span>\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown\">\r\n");
      out.write("            <a href=\"/Solocare/board?category=sell\">판매</a>\r\n");
      out.write("		        <a href=\"/Solocare/board?category=buy\">구매</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"/Solocare/policy\">정책</a>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- 사용자 액션 -->\r\n");
      out.write("  <div class=\"user-actions\">\r\n");
      out.write("    ");
 if (isLoggedIn) { 
      out.write("\r\n");
      out.write("      <div class=\"welcome\">\r\n");
      out.write("        ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mem.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님\r\n");
      out.write("      </div>\r\n");
      out.write("      <a href=\"/Solocare/infocheck\">내정보</a>\r\n");
      out.write("	    <a href=\"/Solocare/logout\">로그아웃</a>\r\n");
      out.write("	    <a href=\"/Solocare/list\">일정관리</a>\r\n");
      out.write("    ");
 } else { 
      out.write("\r\n");
      out.write("      <a href=\"/Solocare/login\" class=\"nav-link\">로그인</a>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"heroSection\">\r\n");
      out.write("    <div class=\"hero-content\" data-aos=\"fade-up\">\r\n");
      out.write("        <a href=\"#bodyWrapper\" class=\"btn-hero\">살펴보기</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 본문 -->\r\n");
      out.write("<div id=\"bodyWrapper\">\r\n");
      out.write("    <div class=\"container-fluid main-container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <!-- 왼쪽: 사이드바 (sticky) -->\r\n");
      out.write("            <div class=\"col-md-3 col-lg-2\">\r\n");
      out.write("                <div class=\"category-sidebar\" data-aos=\"fade-right\">\r\n");
      out.write("                    <h4>카테고리</h4>\r\n");
      out.write("                    <!-- 카테고리 폼 -->\r\n");
      out.write("                    <form id=\"categoryForm\" action=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" method=\"get\">\r\n");
      out.write("                        <ul class=\"category-list\">\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                        </ul>\r\n");
      out.write("\r\n");
      out.write("                        <button type=\"submit\" class=\"btn-category-search\">카테고리 검색</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("\r\n");
      out.write("                    <!-- 사용자 검색 -->\r\n");
      out.write("                    <div class=\"user-search-form\">\r\n");
      out.write("                        <form id=\"searchForm\" action=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" method=\"get\">\r\n");
      out.write("                            <input type=\"text\" \r\n");
      out.write("                                   class=\"form-control\" \r\n");
      out.write("                                   id=\"queryInput\"\r\n");
      out.write("                                   name=\"query\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.query}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                                   placeholder=\"검색어를 입력하세요\">\r\n");
      out.write("\r\n");
      out.write("                            <select id=\"sort\" name=\"sort\" class=\"form-control\" onchange=\"applySort()\">\r\n");
      out.write("                                <option value=\"sim\"        ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.sort == 'sim'        ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">관련도순</option>\r\n");
      out.write("                                <option value=\"price_low\"  ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.sort == 'price_low'  ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">가격 낮은 순</option>\r\n");
      out.write("                                <option value=\"price_high\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.sort == 'price_high' ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">가격 높은 순</option>\r\n");
      out.write("                                <option value=\"date\"       ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.sort == 'date'       ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">최신순</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("\r\n");
      out.write("                            <button type=\"submit\" class=\"btn-user-search\">검색</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div><!-- category-sidebar end -->\r\n");
      out.write("            </div><!-- col-md-3 end -->\r\n");
      out.write("\r\n");
      out.write("            <!-- 오른쪽: 상품 목록 -->\r\n");
      out.write("            <div class=\"col-md-9 col-lg-10\" data-aos=\"fade-up\">\r\n");
      out.write("                <h2 class=\"section-title\">추천 상품</h2>\r\n");
      out.write("                <h3 class=\"section-subtitle\">가구/인테리어</h3>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"row card-grid\">\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fforEach_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <h3 class=\"section-subtitle\">식품</h3>\r\n");
      out.write("                <div class=\"row card-grid\">\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fforEach_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div><!-- col-md-9 end -->\r\n");
      out.write("        </div><!-- row end -->\r\n");
      out.write("    </div><!-- container-fluid end -->\r\n");
      out.write("</div><!-- bodyWrapper end -->\r\n");
      out.write("\r\n");
      out.write("<!-- 푸터 -->\r\n");
      out.write("<footer class=\"mt-4\">\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<footer class=\"bg-light text-dark py-2\">\r\n");
      out.write("    <div class=\"d-flex justify-content-between align-items-center\" style=\"max-width: 1800px; margin: 0 auto; padding-left: 15px; padding-right: 15px;\">\r\n");
      out.write("        <div style=\"font-family: 'Montserrat', sans-serif; font-size: 0.8rem;\">\r\n");
      out.write("            © 2024 Solocare\r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"font-family: 'Montserrat', sans-serif; font-size: 0.8rem;\">\r\n");
      out.write("            <a href=\"/privacy\" class=\"text-dark me-3 text-decoration-none\">개인정보 처리방침</a>\r\n");
      out.write("            <a href=\"/terms\" class=\"text-dark text-decoration-none\">이용약관</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<!-- AOS 라이브러리 JS -->\r\n");
      out.write("<script src=\"https://unpkg.com/aos@2.3.1/dist/aos.js\"></script>\r\n");
      out.write("<!-- AOS 초기화 -->\r\n");
      out.write("<script>\r\n");
      out.write("  document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("    AOS.init({\r\n");
      out.write("      duration: 800, \r\n");
      out.write("      easing: 'ease-in-out',\r\n");
      out.write("      once: true,\r\n");
      out.write("    });\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("  function applySort() {\r\n");
      out.write("    document.getElementById('searchForm').submit();\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  /* 카테고리 라디오 다시 클릭 시 해제 & 하위 토글 */\r\n");
      out.write("  document.querySelectorAll('.category-list input[type=\"radio\"]').forEach(input => {\r\n");
      out.write("      let lastClicked = null;\r\n");
      out.write("      input.addEventListener('click', (e) => {\r\n");
      out.write("          if (lastClicked === input) {\r\n");
      out.write("              input.checked = false;\r\n");
      out.write("              lastClicked = null;\r\n");
      out.write("              const event = new Event('change', { bubbles: true });\r\n");
      out.write("              input.dispatchEvent(event);\r\n");
      out.write("          } else {\r\n");
      out.write("              lastClicked = input;\r\n");
      out.write("          }\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      input.addEventListener('change', () => {\r\n");
      out.write("          const listItem = input.closest('li');\r\n");
      out.write("          if (!listItem) return;\r\n");
      out.write("          const subcategory = listItem.querySelector('.subcategory');\r\n");
      out.write("          if (subcategory && input.checked) {\r\n");
      out.write("              subcategory.classList.add('visible');\r\n");
      out.write("          } else if (subcategory) {\r\n");
      out.write("              subcategory.classList.remove('visible');\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("          // 다른 부분 숨기기\r\n");
      out.write("          document.querySelectorAll('.category-list .subcategory').forEach(sub => {\r\n");
      out.write("              const parent = sub.closest('li');\r\n");
      out.write("              if (sub !== subcategory && !parent.contains(input)) {\r\n");
      out.write("                  sub.classList.remove('visible');\r\n");
      out.write("              }\r\n");
      out.write("          });\r\n");
      out.write("\r\n");
      out.write("          // 하위 레벨 자동 열기\r\n");
      out.write("          const currentLevel = input.name.replace('category', '');\r\n");
      out.write("          const nextLevel = parseInt(currentLevel) + 1;\r\n");
      out.write("          document.querySelectorAll(`input[name=\"category");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nextLevel}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"]`).forEach(nextInput => {\r\n");
      out.write("              const nextListItem = nextInput.closest('li');\r\n");
      out.write("              const nextSubcategory = nextListItem ? nextListItem.querySelector('.subcategory') : null;\r\n");
      out.write("              if (nextInput.checked && nextSubcategory) {\r\n");
      out.write("                  nextSubcategory.classList.add('visible');\r\n");
      out.write("              }\r\n");
      out.write("          });\r\n");
      out.write("      });\r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/views/search.jsp(352,52) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/results");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/views/search.jsp(354,28) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("category1");
    // /WEB-INF/views/search.jsp(354,28) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/search.jsp(354,28) '${categories.keySet()}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${categories.keySet()}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                <li>\r\n");
          out.write("                                    <input type=\"radio\" name=\"category1\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("                                           ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.category1 == category1 ? 'checked' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("                                           id=\"res_cat1_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" />\r\n");
          out.write("                                    <label for=\"res_cat1_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</label>\r\n");
          out.write("\r\n");
          out.write("                                    <ul class=\"subcategory ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.category1 == category1 ? 'visible' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                                        ");
          if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("                                    </ul>\r\n");
          out.write("                                </li>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /WEB-INF/views/search.jsp(362,40) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("category2");
    // /WEB-INF/views/search.jsp(362,40) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/search.jsp(362,40) '${categories[category1].keySet()}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${categories[category1].keySet()}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                            <li>\r\n");
          out.write("                                                <input type=\"radio\" name=\"category2\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("                                                       ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.category2 == category2 ? 'checked' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("                                                       id=\"res_cat2_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" />\r\n");
          out.write("                                                <label for=\"res_cat2_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</label>\r\n");
          out.write("\r\n");
          out.write("                                                <ul class=\"subcategory ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.category2 == category2 ? 'visible' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                                                    ");
          if (_jspx_meth_c_005fforEach_005f2(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("                                                </ul>\r\n");
          out.write("                                            </li>\r\n");
          out.write("                                        ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
    // /WEB-INF/views/search.jsp(370,52) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setVar("category3");
    // /WEB-INF/views/search.jsp(370,52) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/search.jsp(370,52) '${categories[category1][category2]}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${categories[category1][category2]}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
      if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                                        <li>\r\n");
          out.write("                                                            <input type=\"radio\" name=\"category3\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("                                                                   ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.category3 == category3 ? 'checked' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("                                                                   id=\"res_cat3_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" />\r\n");
          out.write("                                                            <label for=\"res_cat3_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</label>\r\n");
          out.write("                                                        </li>\r\n");
          out.write("                                                    ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f2.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /WEB-INF/views/search.jsp(391,54) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/results");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f3.setParent(null);
    // /WEB-INF/views/search.jsp(417,20) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setVar("product");
    // /WEB-INF/views/search.jsp(417,20) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/search.jsp(417,20) '${interiorProducts}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${interiorProducts}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
      if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <div class=\"col-sm-6 col-md-4 col-lg-3 mb-4 d-flex\" data-aos=\"fade-up\">\r\n");
          out.write("                            <div class=\"card w-100\">\r\n");
          out.write("                                <img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"card-img-top\" alt=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                                <div class=\"card-body\">\r\n");
          out.write("                                    ");
          if (_jspx_meth_c_005fchoose_005f0(_jspx_th_c_005fforEach_005f3, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f3))
            return true;
          out.write("\r\n");
          out.write("                                    <p class=\"card-product-name\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("                                    <p class=\"card-price\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("                                    <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.link}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"btn btn-primary mt-auto\" target=\"_blank\">\r\n");
          out.write("                                        구매하기\r\n");
          out.write("                                    </a>\r\n");
          out.write("                                </div>\r\n");
          out.write("                            </div>\r\n");
          out.write("                        </div>\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f3.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f3, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f3)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f3);
    int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
    if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                                        ");
        if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f3))
          return true;
        out.write("\r\n");
        out.write("                                        ");
        if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f3))
          return true;
        out.write("\r\n");
        out.write("                                    ");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f3)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /WEB-INF/views/search.jsp(423,40) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.brand != null && product.brand != '알 수 없음'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
    if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                                            <p class=\"card-brand\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.brand}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</p>\r\n");
        out.write("                                        ");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f3)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                                            <p class=\"card-brand\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.mallName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</p>\r\n");
        out.write("                                        ");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f4 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f4.setParent(null);
    // /WEB-INF/views/search.jsp(443,20) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f4.setVar("product");
    // /WEB-INF/views/search.jsp(443,20) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f4.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/search.jsp(443,20) '${foodProducts}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${foodProducts}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f4 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f4 = _jspx_th_c_005fforEach_005f4.doStartTag();
      if (_jspx_eval_c_005fforEach_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <div class=\"col-sm-6 col-md-4 col-lg-3 mb-4 d-flex\" data-aos=\"fade-up\">\r\n");
          out.write("                            <div class=\"card w-100\">\r\n");
          out.write("                                <img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"card-img-top\" alt=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                                <div class=\"card-body\">\r\n");
          out.write("                                    ");
          if (_jspx_meth_c_005fchoose_005f1(_jspx_th_c_005fforEach_005f4, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f4))
            return true;
          out.write("\r\n");
          out.write("                                    <p class=\"card-product-name\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("                                    <p class=\"card-price\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("                                    <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.link}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"btn btn-primary mt-auto\" target=\"_blank\">\r\n");
          out.write("                                        구매하기\r\n");
          out.write("                                    </a>\r\n");
          out.write("                                </div>\r\n");
          out.write("                            </div>\r\n");
          out.write("                        </div>\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f4[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f4.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f4.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f4, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f4)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f4);
    int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
    if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                                        ");
        if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f4))
          return true;
        out.write("\r\n");
        out.write("                                        ");
        if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f4))
          return true;
        out.write("\r\n");
        out.write("                                    ");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f4)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
    // /WEB-INF/views/search.jsp(449,40) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.brand != null && product.brand != '알 수 없음'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
    if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                                            <p class=\"card-brand\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.brand}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</p>\r\n");
        out.write("                                        ");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f4)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
    int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                                            <p class=\"card-brand\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.mallName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</p>\r\n");
        out.write("                                        ");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
    return false;
  }
}
